### ISSUE TITLE
Support for other 3dconnexion products

### ISSUE THREAD

**Issue by herbertwest3** [johnhw/pyspacenavigator#1]
It would seem simple to support other SpaceMouse products by adjusting the vendor and product ids for the HID device.  I tried [0x256f,0xc62e](tethered) and [0x256f,0xc62f](wireless) for the SpaceMouse Wireless, and was then able to turn on and off the LED with set_led() but never received any data callbacks. Any thoughts? Would love to get this working; pyspacenavigator is exactly what I need.

**Comment by johnhw** [comment]
Yes, it should be easy enough. I'll make some changes to support multiple device types. I think the data encoding (or at least the channel IDs used) might be different for your device, but it is easy enough to determine this. I'll add a script that dumps the raw HID stream to terminal so you can see what changes are happening when you move the Wireless, and then I can modify the callback code to work with that output.

**Comment by johnhw** [comment]
OK, the latest version (0.1.5) can support multiple devices. We just need to work out what the format for the Wireless device is. If you run the [raw_data.py](https://github.com/rene-aguirre/pywinusb/blob/master/examples/raw_data.py) script from pywinusb you should be able to see the raw data stream from the device. 
The format seems to be
[channel, a1, a2, b1, b2, c1, c2], where a1,a2 etc form a 16 bit values. The buttons on my device are just:
[channel, button_bits, 0, 0, 0, 0, 0]

If you can work out what the values are for the 6 axes and buttons on your device, you can add a new entry to device_specs in spacenavigator.py; send a pull request and I'll add it in. (or post them here and I can add them in)

**Comment by herbertwest3** [comment]
(i just noticed the above replies hiding in my inbox).  thank you, i will take a look as soon as i can and feed back some information to you.

**Comment by PaulMichaelPhillips** [comment]
Hi @johnhw 

I am trying to get this to work with a wireless SpaceMouse. It connects successfully (once the id's have been changed) but the data once formatted is always 0. Do you have an idea as to what alteration is required to get the data formatted correctly?

Regards,
Paul

**Comment by johnhw** [comment]
Can you run the raw_data.py script mentioned above (from the pywinusb package) to dump the HID stream while you adjust the SpaceMouse? If you adjust the mouse on each axis (as best you can) and try each button, you should be able to see which channels are carrying the axis data. I assume a new entry in the device_specs dictionary will be required to support the device.

**Comment by PalantirWielder** [comment]
Hey there @johnhw,
Today I was looking around for ways to access my SpaceMouse Pro Wireless' values and I came across your library. It's pretty cool.

I also tried to use the library with my SpaceMouse but:
- The VID & PID needed to be changed for my device
- I too was getting all zeroes in the read values

So following your suggestion for using raw_hid.py I was able to reverse out the protocol alterations for the 6-axes and the 15 buttons. I've since updated my local `spacenavigator.py` to decode and output the 6-axes values. And I'm in the process of designing how to integrate the multiple buttons into your code with the smallest code disturbance.

1. Once I've completed the code alteration I'll fork your library so you can see the changes. In addition to that, would you be interested in my creating a Pull Request to submit the fork, after we discuss any alterations that you'd like? 

2. My current plan is to simply alter the code to work _only_ with the SpaceMouse Pro Wireless that I'm working with. Once you've had a chance to look over my code, I'd be interested to hear any suggestions for having the two different devices co-exist in the code. I think the key difference will be in how buttons are specified in the different device configurations.

3. Do you have a vision for how I could extend your code to handle the 15 buttons that my device has? I'm sure I could come up with something on my own, but perhaps you'd have a more concise design given it's your code.

Just let me know how you'd like to collaborate, if at all.

**Comment by johnhw** [comment]
@PalantirWielder 
Yes, very happy to have this added. Please make a PR.

I have just modified the code (1c815eb) to make the button state be a list of (binary) integers, which will make it easier to support 15 buttons. The old code could support multiple buttons by adding new entries into the button_mapping list, but this will end up packed into a single integer as a bit array which is pretty inconvenient.

With the tweaked code, just add the buttons into button_mapping, specifying the byte+bit of the HID event to look at, and the button state will be written into that element of the button vector.

Note all that you need to is add a new entry to device_specs for the SpaceMouse Pro Wireless. It will then autodetect the right device and use it; you don't need to change or remove the SpaceNavigator.

**Comment by PalantirWielder** [comment]
@johnhw
Excellent. I've downloaded your latest code and ported my changes over to the new format. I'll test the SpaceMouse Pro changes tomorrow.

I have a SpaceNavigator on hand, so I tested that in the meantime. Assuming that I'm correctly understanding the formatting of the ButtonSpec, I believe that there were a few changes that weren't implemented to handle the new format. I updated the SpaceNavigator's device_specs for button_mapping so that it had a ButtonSpec for each of the two buttons. I then propagated that change through the code to restore the testing button_callback functionality.

All these changes will be in the PR I'll file after I can confirm the SpaceMouse Pro code works as desired.

Thanks for the quick response!

**Comment by PalantirWielder** [comment]
@johnhw
I've [forked](https://github.com/PalantirWielder/pyspacenavigator) the repository, made the changes to the code, and tested it on both the SpaceMouse Pro Wireless, as well as the SpaceNavigator (3DX-700028).

The SpaceMouse Pro appears to work as desired.

One thing that popped up was the value scaling of the aforementioned SpaceNavigator. When moving the puck to it's extremes, I noticed that the values were of a greater magnitude than 1.0.
I then changed the scaling to 1.0 temporarily and looked for the min/max values for each axis:
x	[-441.0, 446.0]
y	[-471.0, 498.0]
z	[-458.0, 445.0]
roll	[-454.0, 409.0]
pitch	[-439.0, 445.0]
yaw	[-420.0, 413.0]

I also jumped to a commit prior to your recent changes, and the scaling phenomenon was still present. Is it a problem if the output values are greater than 1.0?

Since functionality appears to be working properly, beside the odd scaling quirk, I'll go ahead and file a PR. Then in that thread we can discuss any additional changes you'd like made before the merge.

**Comment by johnhw** [comment]
Thanks for the PR! I will investigate the SpaceNavigator scaling issue on my device -- perhaps the device axis range is different on different versions or can be user modified?

**Comment by johnhw** [comment]
Hmm, can't see why the SpaceNavigator would report these values -- mine maxes out at [-350.0, 350.0], and so scales to exactly [-1.0, 1.0] with the default scaling. The latest commit prints out the vendor name, device name and version number as reported by the device itself. I get:

     SpaceNavigator connected to 3Dconnexion SpaceNavigator version: 1077 [serial: ]

Do you have a different HW version? It could also be that the range is configurable in firmware.

**Comment by PalantirWielder** [comment]
My pleasure! It nice when my work can be contributed back to the community.

1. When I went to execute the updated code, it failed to run because _serial_number_ is considered unicode, and the value that it contains wasn't a known character, on my system at least.
```
Devices found:
        SpaceNavigator
SpaceNavigator found
Traceback (most recent call last):
  File "spacenavigator.py", line 347, in <module>
    print(dev.describe_connection())
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0000' in position 78: character maps to <undefined>
```
_FYI, I changed the serial number to all zeroes when I pasted it here_

2. After working around that issue, I received this output:
`SpaceNavigator connected to 3Dconnexion SpaceNavigator version: 1028`

So yes, it is a different version. Not sure if that's a firmware version or a hardware version, but it is different.

**Comment by PalantirWielder** [comment]
Oh, and one other thing. I don't believe the SpaceMouse Pro has a controllable LED, unlike the SpaceNavigator. Is there a way to verify that there is no interface to one?

**Comment by giant99** [comment]
Hello, I'm trying to modify the code to include the SpaceMouse Enterprise. I have added SpaceMouse Enterprise to the supported devices list and now it recognizes it. But nothing else is happening. I have run the raw_data.py script as suggested and Have the following strings
Raw data: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
When using the device the channel remains 1 for the axis directions 
If we set object moving left-right as X axis, zoom in-out as Y axis, and up-down as Z axis then
Raw data: [1, X, X, Y, Y, Z, Z, R, R, P, P, Y, Y]

Please let me know where I need to change the code. I'm not really familiar with working with this level of complicated scripting.

Thanks

**Comment by aephchw** [comment]
Hi, 
thank you johnhw for your work!
I am trying to use it with the SpaceMouse Enterprise but can't succeed.
@giant99: could you figure it out? 
Thanks in advance

**Comment by johnhw** [comment]
@aephchw you might want to look at the automatic branch. It will autodetect the device capabilities from the HID usage pages for any detected device. Unfortunately, I can't get buttons to work correctly with this mode on Windows, but it should be enough for you to get the axes specifications to use in the master branch version.

**Comment by aephchw** [comment]
ok, thank you. Until now I already figured out how to connect with it and read its status which already works fine for me (I don't need the buttons, just x,y,z coordinates).
Currently I am not sure, if the axis are correct as I copied them from the SpaceMouse Pro, but at least I do get values.
Next step is implementing it in a GUI..

**Comment by giant99** [comment]
Hey,

I was able to get it working, at least the coordinates. I am attaching the
modified script.

I have not been able to spend the time to get the buttons working properly.
If anyone has those working for the SpaceMouse Enterprise please let me
know.

Thanks

**Comment by Mindbulletz** [comment]
My 3dconnexion device (SpaceMouse Wireless) creates six nearly identical devices. vID=0x256f, pID=0xc652, for each one. Only one of them outputs the data.

I've created a profile for the device already, but I can't figure out how to select between the device's instances more granularly than vID and pID. Is there one in pyspacenavigator or am I better off custom-writing something based on the raw_data.py example?

**Comment by TheOfficialDarthVader** [comment]
I've noticed the code here on GitHub includes support for the SpaceMouse Compact but this is not the case when installing the library with pip

**Comment by levinivel** [comment]
Hi, can you add the product "SpaceMouse Module USB" (https://3dconnexion.com/us/product/spacemouse-module/) as well to the list? This version is not supported by 3DConnexion's libraries, so a solution such as pyspacemouse is perfect for those users.

**Comment by Niyati20** [comment]
Anyone figure out how to use Spacemouse Enterprise with Pyspacemouse or add it to this library?

**Comment by bksel** [comment]
Hi, would it be hard to implement support for SpaceMouse Enterprise with all its basic keys - the same ones that are with SpaceMouse Pro? Would it be matter of switching parameters defined for SpaceMouse Pro, or it would be harder?

**Comment by Daydream-hrb** [comment]
Hi everyone!
My device is 3Dx SpaceMouse Wireless. I went though all the suggestions in this page and finally succeeded. Maybe I can make a record here and give hints to programmers for their future projects.
The problems I met are as follows:

1. No device found.
2. All zero output.
3. It seems to be multiple 3Dx devices sharing the same name and id.

My steps to solve are as follows:

1. Remove the 3Dconnexion software. This step may be unnecessary if you make sure that the 3Dx software is not working when you read the data via Python.
2. Run [raw_data.py](https://github.com/rene-aguirre/pywinusb/blob/master/examples/raw_data.py) as @johnhw wisely suggested and find out the exact index of your device. This step is kind of confusing in that I found 6 3Dx devices with the same name and id. Therefore I tried them one by one. And once you select the correct device index, there will be outputs when you move your spacemouse.
3. Modify [spacenavigator.py](https://github.com/johnhw/pyspacenavigator/blob/master/spacenavigator.py) > **class DeviceSpec(object)** > **device_specs**. Make sure the **name** and **hid_id** are correct (you can copy the **hid_id** from `step 2`).
4. Modify  [spacenavigator.py](https://github.com/johnhw/pyspacenavigator/blob/master/spacenavigator.py) > **def open** (not the one under **class DeviceSpec(object)**). The modification is shown below:
```
# PRE:
all_hids = hid.find_all_hid_devices()
    if all_hids:
        for index, dev in enumerate(all_hids):

# NEW:
all_hids = hid.find_all_hid_devices()
    if all_hids:
        dev = all_hids[6]
```
The number 6 is the index number (in `step 2`) **minus 1**. This number 6 is the correct device in my computer and may not be the same in yours. The reason why I manually select the device here comes from `problem 3` I mentioned above. When there are lots of devices sharing the same name and id, pyspacenavigator fails to select the right one. But I'm not sure whether this `problem 3` is a common phenomenon or not.

5. Run [Basic Usage](https://github.com/johnhw/pyspacenavigator/) and watch the printed state.
![image](https://github.com/johnhw/pyspacenavigator/assets/122712227/dfdfa4ee-d0af-4e31-8a65-0216b35bcf56)


The 5 steps above is how I finally suceeded. And hopefully you will, too!

**Comment by richard-sim** [comment]
erm, `device_specs` is a dictionary, but you're using identical keys (for which only the last one will be used) e.g. `"SpaceMouse Pro Wireless"`. They should probably be renamed to `"SpaceMouse Pro Wireless (wired)"` and `"SpaceMouse Pro Wireless Receiver"`.

On a related note, if you're not aware, you can find all the relevant hid/pid pairs by searching for "3dconnexion" here: http://www.linux-usb.org/usb.ids
